stages:
  - build
  - test

build:gnu:
  stage: build
  tags:
    - darwin-slurm-shared
  script:
    - source envScripts/darwin-gnu.sh
    - make all
    - make test
  artifacts:
    paths:
    - alinterface_f.mod
    - libalGlue.a
    - sniffTest_serial
    - sniffTest_mpi
    expire_in: 1 day

build:intel:
  stage: build
  tags:
    - darwin-slurm-shared
  script:
    - source envScripts/darwin-intel.sh
    - make all CC=icpc CXX=icpc FC=ifort MPICXX=mpicxx
    - make test CC=icpc CXX=icpc FC=ifort MPICXX=mpicxx
  artifacts:
    paths:
    - alinterface_f.mod
    - libalGlue.a
    - sniffTest_serial
    - sniffTest_mpi
    expire_in: 1 day

build:clang:
  stage: build
  tags:
    - darwin-slurm-shared
  script:
    - source envScripts/darwin-clang.sh
    - make all CC=clang CXX=clang++ FC=gfortran
    - make test CC=clang CXX=clang++ FC=gfortran
  artifacts:
    paths:
    - alinterface_f.mod
    - libalGlue.a
    - sniffTest_serial
    - sniffTest_mpi
    expire_in: 1 day

test:gnu:
  stage: test
  tags:
   - darwin-slurm-shared
  script:
    - source envScripts/darwin-gnu.sh
    - mkdir serial && cd serial
    - bash ../sniffTest_serial.sh
  needs: ["build:gnu"]
  dependencies:
    - build:gnu

test:gnu_mpi:
  stage: test
  tags:
    - darwin-slurm-shared
  script:
    - source envScripts/darwin-gnu.sh
    - mkdir mpi && cd mpi
    - bash ../sniffTest_mpi.sh
  needs: ["build:gnu"]
  dependencies:
    - build:gnu

test:intel:
  stage: test
  tags:
   - darwin-slurm-shared
  script:
    - source envScripts/darwin-intel.sh
    - mkdir serial && cd serial
    - bash ../sniffTest_serial.sh
  needs: ["build:intel"]
  dependencies:
    - build:intel

test:clang:
  stage: test
  tags:
   - darwin-slurm-shared
  script:
    - source envScripts/darwin-clang.sh
    - mkdir serial && cd serial
    - bash ../sniffTest_serial.sh
  needs: ["build:clang"]
  dependencies:
    - build:clang
